server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 80 #启动端口
spring:
    application:
        name: xialin
 #数据库链接
    datasource:
        url: jdbc:mysql://localhost:3306/biz?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    resources:
        static-locations: classpath:/static/,classpath:/views/
    freemarker:
      cache: false
      settings:
        template_update_delay: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml